FROM node:18.19.0-bookworm

RUN apt-get update && apt-get install -y \
  nano

# Create app directory
WORKDIR /app

COPY package*.json ./

RUN npm install

# Bundle app source
COPY . .

EXPOSE 3000

CMD [ "node", "index.js" ]
